import { motion } from "motion/react";
import { 
  Cpu, 
  Users, 
  Map, 
  Zap, 
  Target, 
  ArrowRight, 
  CheckCircle,
  Wrench,
  Sparkles,
  Sprout,
  Brain,
  Globe
} from "lucide-react";

const FeatureDetailCard = ({ icon: Icon, title, description, advantages, helpPoints, colorClass, delay }: any) => {
  return (
    <motion.div
      initial={{ opacity: 0, y: 10 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-100px" }}
      transition={{ duration: 1.2, delay, ease: [0.23, 1, 0.32, 1] }}
      className={`glass-dark p-8 md:p-16 rounded-[2.5rem] md:rounded-[3.5rem] border border-white/5 relative overflow-hidden group max-w-5xl mx-auto transition-all duration-700 hover:border-white/20`}
    >
      <div className={`absolute top-0 right-0 w-[500px] h-[500px] blur-[150px] opacity-5 transition-opacity group-hover:opacity-15 ${colorClass}`} />
      
      <div className="relative z-10">
        <div className={`w-16 h-16 md:w-20 md:h-20 rounded-2xl md:rounded-3xl flex items-center justify-center mb-8 md:mb-10 ${colorClass.replace('blur-[150px]', '')} bg-opacity-5 border border-white/5`}>
          <Icon className="w-8 h-8 md:w-10 md:h-10" />
        </div>
        
        <h3 className="text-4xl md:text-7xl font-display font-bold mb-6 md:mb-8 tracking-tight leading-[1.1] md:leading-[0.9]">{title}</h3>
        <p className="text-white/60 text-lg md:text-xl mb-10 md:mb-12 leading-relaxed font-light max-w-2xl">
          {description}
        </p>
        
        <div className="grid sm:grid-cols-2 gap-12 pt-12 border-t border-white/5">
          <div>
            <h4 className="text-[10px] font-bold uppercase tracking-[0.4em] text-white/20 mb-8 flex items-center gap-3">
              <Zap className="w-4 h-4 text-brand-blue" /> Advantages
            </h4>
            <ul className="space-y-5">
              {advantages.map((adv: string, i: number) => (
                <li key={i} className="flex items-start gap-4 text-white/60 text-base leading-relaxed font-light">
                  <CheckCircle className="w-5 h-5 text-brand-green shrink-0 mt-0.5" />
                  <span>{adv}</span>
                </li>
              ))}
            </ul>
          </div>
          
          <div>
            <h4 className="text-[10px] font-bold uppercase tracking-[0.4em] text-white/20 mb-8 flex items-center gap-3">
              <Target className="w-4 h-4 text-brand-orange" /> Impact
            </h4>
            <ul className="space-y-5">
              {helpPoints.map((point: string, i: number) => (
                <li key={i} className="flex items-start gap-4 text-white/60 text-base leading-relaxed font-light">
                  <div className="w-2 h-2 rounded-full bg-brand-blue shrink-0 mt-2.5" />
                  <span>{point}</span>
                </li>
              ))}
            </ul>
          </div>
        </div>
      </div>
    </motion.div>
  );
};

const FeaturesPage = () => {
  const features = [
    {
      icon: Brain,
      title: "AI Roadmaps",
      description: "Hyper-personalized strategies generated by our proprietary neural networks, evolving with your progress and market shifts.",
      advantages: [
        "Dynamic path recalculation",
        "Deep neural goal analysis",
        "Progress-synced milestones",
        "Multi-variable risk assessment"
      ],
      helpPoints: [
        "Eliminates decision fatigue",
        "Provides 24/7 strategic clarity",
        "Identifies hidden opportunities",
        "Ensures consistent momentum"
      ],
      colorClass: "bg-brand-green/20 text-brand-green",
      delay: 0.1
    },
    {
      icon: Users,
      title: "Elite Mentors",
      description: "Direct connection to industry titans and life coaches who provide the critical human context and empathy AI cannot.",
      advantages: [
        "1-on-1 strategic sessions",
        "Industry-specific networking",
        "Emotional intelligence coaching",
        "Real-world experience sharing"
      ],
      helpPoints: [
        "Builds high-level confidence",
        "Provides nuanced feedback",
        "Opens exclusive career doors",
        "Fosters long-term resilience"
      ],
      colorClass: "bg-brand-blue/20 text-brand-blue",
      delay: 0.2
    },
    {
      icon: Sprout,
      title: "Agri-Tech Solutions",
      description: "Revolutionizing the backbone of society with modern data insights, satellite imagery, and sustainable growth strategies.",
      advantages: [
        "Precision soil analysis",
        "Weather-predictive modeling",
        "Supply chain optimization",
        "Sustainable yield strategies"
      ],
      helpPoints: [
        "Increases crop productivity",
        "Reduces resource wastage",
        "Connects farmers to markets",
        "Ensures food security"
      ],
      colorClass: "bg-brand-orange/20 text-brand-orange",
      delay: 0.3
    },
    {
      icon: Wrench,
      title: "AI Tools Suite",
      description: "A comprehensive toolkit of proprietary AI-driven utilities designed to automate complex tasks and provide deep analytical insights.",
      advantages: [
        "Automated workflow builders",
        "Real-time data visualization",
        "Predictive trend analysis",
        "Cross-platform integration"
      ],
      helpPoints: [
        "Saves 20+ hours per week",
        "Minimizes operational errors",
        "Scales with your business",
        "Empowers data-driven choices"
      ],
      colorClass: "bg-brand-blue/20 text-brand-blue",
      delay: 0.4
    },
    {
      icon: Globe,
      title: "Community Ecosystem",
      description: "A vibrant global network connecting ambitious individuals with world-class mentors and like-minded peers for collaborative growth.",
      advantages: [
        "Global peer-to-peer learning",
        "Exclusive masterclass access",
        "Collaborative project hubs",
        "Regional chapter support"
      ],
      helpPoints: [
        "Fosters a growth mindset",
        "Provides diverse perspectives",
        "Accelerates skill acquisition",
        "Creates lifelong connections"
      ],
      colorClass: "bg-brand-green/20 text-brand-green",
      delay: 0.5
    },
    {
      icon: Map,
      title: "AI Journey Map",
      description: "Your dynamic, AI-generated visual roadmap that evolves in real-time based on your progress, goals, and changing conditions.",
      advantages: [
        "Visual progress tracking",
        "Adaptive milestone shifts",
        "Skill-gap identification",
        "Long-term goal alignment"
      ],
      helpPoints: [
        "Maintains focus on 'North Star'",
        "Prevents goal-related stress",
        "Celebrates micro-wins",
        "Ensures no step is missed"
      ],
      colorClass: "bg-brand-orange/20 text-brand-orange",
      delay: 0.6
    }
  ];

  return (
    <div className="min-h-screen bg-bg pt-40 pb-20 overflow-hidden">
      {/* Background Accents */}
      <div className="fixed inset-0 pointer-events-none">
        <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] bg-brand-blue/5 blur-[150px] rounded-full" />
        <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] bg-brand-green/5 blur-[150px] rounded-full" />
      </div>

      <div className="max-w-7xl mx-auto px-6 relative z-10">
        <div className="text-center mb-40">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="inline-flex items-center gap-2 px-5 py-2 glass rounded-full text-brand-blue text-[10px] font-bold uppercase tracking-[0.3em] mb-10 border-brand-blue/20 glow-blue"
          >
            <Sparkles className="w-4 h-4" /> The IAH Ecosystem
          </motion.div>
          
          <motion.h1
            initial={{ opacity: 0, y: 40 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.1, duration: 1, ease: [0.16, 1, 0.3, 1] }}
            className="text-7xl md:text-[140px] font-display font-bold mb-12 tracking-tight leading-[0.8]"
          >
            Empowering Your <br />
            <span className="text-gradient italic font-light">Future</span>
          </motion.h1>
          
          <motion.p
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2, duration: 0.8 }}
            className="text-white/60 text-xl md:text-2xl max-w-3xl mx-auto font-light leading-relaxed tracking-tight"
          >
            IAH.AI is more than a platform; it's a multi-dimensional intelligence engine designed to bridge the gap between potential and peak performance.
          </motion.p>
        </div>

        <div className="space-y-32">
          {features.map((feature, index) => (
            <FeatureDetailCard key={index} {...feature} />
          ))}
        </div>

        {/* Full Ecosystem Overview */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          className="mt-40 max-w-4xl mx-auto"
        >
          <div className="text-center mb-16">
            <h2 className="text-4xl md:text-5xl font-display font-bold mb-8 leading-tight">
              A Holistic Approach to <span className="text-brand-green">Human Evolution</span>
            </h2>
            <p className="text-white/60 text-lg mb-8 leading-relaxed max-w-2xl mx-auto">
              At IAH.AI, we don't just provide tools; we create a synergy between artificial intelligence and human intuition. Our ecosystem is built on the belief that technology should amplify human potential, not replace it.
            </p>
          </div>
          
          <div className="grid md:grid-cols-3 gap-8 perspective-1000">
            {[
              { title: "Neural Integration", desc: "Our AI models are trained to understand human context and emotional intelligence." },
              { title: "Global Network", desc: "Connect with a worldwide community of innovators and leaders." },
              { title: "Sustainable Growth", desc: "Long-term strategies that focus on both professional and personal well-being." }
            ].map((item, i) => (
              <div key={i} className="glass-dark p-8 rounded-3xl border border-white/5 text-center group hover:border-brand-green/30 transition-colors hover-3d preserve-3d">
                <div className="w-12 h-12 rounded-xl bg-white/5 border border-white/10 flex items-center justify-center mx-auto mb-6">
                  <div className="w-2 h-2 rounded-full bg-brand-green" />
                </div>
                <h4 className="font-bold mb-3 text-lg">{item.title}</h4>
                <p className="text-white/60 text-sm leading-relaxed">{item.desc}</p>
              </div>
            ))}
          </div>
        </motion.div>

        {/* Call to Action */}
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          whileInView={{ opacity: 1, scale: 1 }}
          viewport={{ once: true }}
          className="mt-40 glass-dark p-16 rounded-[3rem] border border-white/5 text-center relative overflow-hidden"
        >
          <div className="absolute inset-0 bg-gradient-to-br from-brand-blue/10 via-transparent to-brand-green/10 opacity-50" />
          <div className="relative z-10">
            <h2 className="text-4xl md:text-6xl font-display font-bold mb-8">Ready to start your <span className="text-gradient italic">Journey?</span></h2>
            <p className="text-white/60 text-xl mb-12 max-w-2xl mx-auto">
              Join thousands of others who are already using IAH.AI to transform their dreams into reality.
            </p>
            <div className="flex flex-col md:flex-row items-center justify-center gap-6">
              <button 
                aria-label="Join the Waitlist"
                className="px-10 py-5 bg-brand-blue text-white rounded-2xl font-bold text-lg hover:bg-brand-blue/80 transition-all flex items-center gap-3 group focus-visible:outline-2 focus-visible:outline-brand-blue focus-visible:outline-offset-4"
              >
                Join the Waitlist <ArrowRight className="w-5 h-5 group-hover:translate-x-1 transition-transform" />
              </button>
              <button 
                aria-label="Learn more about IAH.AI"
                className="px-10 py-5 bg-white/5 border border-white/10 text-white rounded-2xl font-bold text-lg hover:bg-white/10 transition-all focus-visible:outline-2 focus-visible:outline-white focus-visible:outline-offset-4"
              >
                Learn More
              </button>
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default FeaturesPage;
